_wandb:
    value:
        cli_version: 0.23.1
        e:
            oo5fk9t8yfi0lhactnh5gso6im51zd1r:
                args:
                    - --data_path
                    - preprocessing/data/final_train_data.txt
                    - --vocab_path
                    - preprocessing/data/vocab.json
                    - --output_dir
                    - output
                    - --d_model
                    - "64"
                    - --num_layers
                    - "2"
                    - --num_heads
                    - "4"
                    - --ff_dim
                    - "128"
                    - --dropout_rate
                    - "0.1"
                    - --deep_rec_cycles
                    - "2"
                    - --num_l_steps
                    - "3"
                    - --deep_sup_steps
                    - "2"
                    - --act_loss_weight
                    - "0.1"
                    - --epochs
                    - "15"
                    - --batch_size
                    - "8"
                    - --learning_rate
                    - "1e-4"
                    - --max_seq_length
                    - "128"
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 32
                cpu_count_logical: 32
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "201622011904"
                        used: "9078349824"
                email: benjamin_peckham@brown.edu
                executable: /users/bpeckham/.conda/envs/tinyai/bin/python
                git:
                    commit: 9f149c730f883dedc7fa0114edb57a5b1abad43a
                    remote: git@github.com:rajveer-sodhi/TinyAI.git
                gpu: NVIDIA TITAN RTX
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 4608
                      memoryTotal: "25769803776"
                      name: NVIDIA TITAN RTX
                      uuid: GPU-39b7f90c-f7f0-1ae1-6c47-91b549c94170
                host: gpu1402.oscar.ccv.brown.edu
                memory:
                    total: "403244027904"
                os: Linux-5.14.0-284.11.1.el9_2_cifs.x86_64-x86_64-with-glibc2.34
                program: /oscar/home/bpeckham/TinyAI/train.py
                python: CPython 3.10.19
                root: /oscar/home/bpeckham/TinyAI
                slurm:
                    cluster_name: (null)
                    conf: /var/spool/slurmd/conf-cache/slurm.conf
                    cpus_on_node: "4"
                    cpus_per_task: "4"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: default
                    job_cpus_per_node: "4"
                    job_end_time: "1765397105"
                    job_gid: "20055"
                    job_gpus: "2"
                    job_id: "14775432"
                    job_name: TinyAI
                    job_nodelist: gpu1402
                    job_num_nodes: "1"
                    job_partition: gpu
                    job_qos: norm-gpu
                    job_start_time: "1765382705"
                    job_uid: "140630026"
                    job_user: bpeckham
                    jobid: "14775432"
                    localid: "0"
                    mem_per_node: "64000"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: gpu1402
                    nprocs: "1"
                    ntasks: "1"
                    ntasks_per_node: "1"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    submit_dir: /oscar/home/bpeckham/TinyAI
                    submit_host: login010
                    task_pid: "69041"
                    tasks_per_node: "1"
                    topology_addr: gpu6.gpu1402
                    topology_addr_pattern: switch.node
                    tres_per_task: cpu:4
                startedAt: "2025-12-10T16:05:26.380776Z"
                writerId: oo5fk9t8yfi0lhactnh5gso6im51zd1r
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 2
                - 3
            "2":
                - 2
                - 3
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.19
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
d_model:
    value: 64
epochs:
    value: 15
learning_rate:
    value: 0.0001
model:
    value: control_transformer
num_heads:
    value: 4
num_layers:
    value: 2
