_wandb:
    value:
        cli_version: 0.23.1
        e:
            0jcgunq3qa9x4qnt0bwsnpkuakozr4nl:
                args:
                    - --data_path
                    - preprocessing/data/final_train_data.txt
                    - --vocab_path
                    - preprocessing/data/vocab.json
                    - --output_dir
                    - output
                    - --d_model
                    - "256"
                    - --num_layers
                    - "2"
                    - --num_heads
                    - "4"
                    - --ff_dim
                    - "512"
                    - --dropout_rate
                    - "0.1"
                    - --deep_rec_cycles
                    - "3"
                    - --num_l_steps
                    - "6"
                    - --deep_sup_steps
                    - "4"
                    - --act_loss_weight
                    - "0.1"
                    - --epochs
                    - "20"
                    - --batch_size
                    - "32"
                    - --learning_rate
                    - "1e-4"
                    - --max_seq_length
                    - "256"
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 32
                cpu_count_logical: 32
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "201618690048"
                        used: "16109191168"
                email: benjamin_peckham@brown.edu
                executable: /users/bpeckham/.conda/envs/tinyai/bin/python
                git:
                    commit: 232f50cae914d1664c921cf342d8c29ad8d73edd
                    remote: git@github.com:rajveer-sodhi/TinyAI.git
                gpu: Quadro RTX 6000
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 4608
                      memoryTotal: "25769803776"
                      name: Quadro RTX 6000
                      uuid: GPU-f074dd20-5b07-4729-a690-309885d8718a
                host: gpu2002.oscar.ccv.brown.edu
                memory:
                    total: "403237384192"
                os: Linux-5.14.0-284.11.1.el9_2_cifs.x86_64-x86_64-with-glibc2.34
                program: /oscar/home/bpeckham/TinyAI/train.py
                python: CPython 3.10.19
                root: /oscar/home/bpeckham/TinyAI
                slurm:
                    cluster_name: (null)
                    conf: /var/spool/slurmd/conf-cache/slurm.conf
                    cpus_on_node: "4"
                    cpus_per_task: "4"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: default
                    job_cpus_per_node: "4"
                    job_end_time: "1765355869"
                    job_gid: "20055"
                    job_gpus: "3"
                    job_id: "14764985"
                    job_name: TinyAI
                    job_nodelist: gpu2002
                    job_num_nodes: "1"
                    job_partition: gpu
                    job_qos: norm-gpu
                    job_start_time: "1765341469"
                    job_uid: "140630026"
                    job_user: bpeckham
                    jobid: "14764985"
                    localid: "0"
                    mem_per_node: "32000"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: gpu2002
                    nprocs: "1"
                    ntasks: "1"
                    ntasks_per_node: "1"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    submit_dir: /oscar/home/bpeckham/TinyAI
                    submit_host: login009
                    task_pid: "1400672"
                    tasks_per_node: "1"
                    topology_addr: gpu5.gpu2002
                    topology_addr_pattern: switch.node
                    tres_per_task: cpu:4
                startedAt: "2025-12-10T04:38:17.445185Z"
                writerId: 0jcgunq3qa9x4qnt0bwsnpkuakozr4nl
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 2
                - 3
            "2":
                - 2
                - 3
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.19
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
d_model:
    value: 256
epochs:
    value: 20
learning_rate:
    value: 0.0001
model:
    value: control_transformer
num_heads:
    value: 4
num_layers:
    value: 2
