_wandb:
    value:
        cli_version: 0.23.1
        e:
            dsmrla21pwnuek93apdd16gd3r7588mj:
                args:
                    - --data_path
                    - preprocessing/data/final_train_data.txt
                    - --vocab_path
                    - preprocessing/data/vocab.json
                    - --output_dir
                    - output
                    - --d_model
                    - "128"
                    - --num_layers
                    - "2"
                    - --num_heads
                    - "4"
                    - --ff_dim
                    - "256"
                    - --dropout_rate
                    - "0.1"
                    - --deep_rec_cycles
                    - "4"
                    - --num_l_steps
                    - "6"
                    - --deep_sup_steps
                    - "4"
                    - --act_loss_weight
                    - "0.01"
                    - --step_penalty_weight
                    - "0.001"
                    - --min_halt_steps
                    - "3"
                    - --stage_weights
                    - 1.0,1.5,2.0,2.5
                    - --epochs
                    - "15"
                    - --batch_size
                    - "8"
                    - --learning_rate
                    - "1e-4"
                    - --max_seq_length
                    - "128"
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 64
                cpu_count_logical: 64
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "540490342400"
                        used: "8933171200"
                email: benjamin_peckham@brown.edu
                executable: /users/bpeckham/.conda/envs/tinyai/bin/python
                git:
                    commit: 6b1874b8ef068dbdfe0bbcdd444004e0e6a2e0f2
                    remote: git@github.com:rajveer-sodhi/TinyAI.git
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-afc79912-340a-b847-8a37-7e9cb6cd6fcb
                host: gpu2101.oscar.ccv.brown.edu
                memory:
                    total: "1080980684800"
                os: Linux-5.14.0-284.11.1.el9_2_cifs.x86_64-x86_64-with-glibc2.34
                program: /oscar/home/bpeckham/TinyAI/train.py
                python: CPython 3.10.19
                root: /oscar/home/bpeckham/TinyAI
                slurm:
                    cluster_name: (null)
                    conf: /var/spool/slurmd/conf-cache/slurm.conf
                    cpus_on_node: "4"
                    cpus_per_task: "4"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: default
                    job_cpus_per_node: "4"
                    job_end_time: "1765589647"
                    job_gid: "20055"
                    job_gpus: "0"
                    job_id: "14823519"
                    job_name: TinyAI
                    job_nodelist: gpu2101
                    job_num_nodes: "1"
                    job_partition: gpu
                    job_qos: norm-gpu
                    job_start_time: "1765575247"
                    job_uid: "140630026"
                    job_user: bpeckham
                    jobid: "14823519"
                    localid: "0"
                    mem_per_node: "64000"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: gpu2101
                    nprocs: "1"
                    ntasks: "1"
                    ntasks_per_node: "1"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    submit_dir: /oscar/home/bpeckham/TinyAI
                    submit_host: login009
                    task_pid: "190343"
                    tasks_per_node: "1"
                    topology_addr: 30901.gpu2101
                    topology_addr_pattern: switch.node
                    tres_per_task: cpu:4
                startedAt: "2025-12-12T21:34:44.616036Z"
                writerId: dsmrla21pwnuek93apdd16gd3r7588mj
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 2
                - 3
            "2":
                - 2
                - 3
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.19
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
d_model:
    value: 128
epochs:
    value: 15
learning_rate:
    value: 0.0001
model:
    value: control_transformer
num_heads:
    value: 4
num_layers:
    value: 2
